language: go

go:
  - 1.11.x

addons:
  apt:
    packages:
      - rpm

env:
  - GO111MODULE=on

script:
  - go build -o mtr # currently there are no tests avaiable ...
  - git reset --hard

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

